// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WaID,
		&i.FromJid,
		&i.ToJid,
		&i.Content,
		&i.MediaType,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByWAID = `-- name: GetMessageByWAID :one
SELECT id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at FROM messages WHERE wa_id = ? LIMIT 1
`

func (q *Queries) GetMessageByWAID(ctx context.Context, waID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByWAID, waID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WaID,
		&i.FromJid,
		&i.ToJid,
		&i.Content,
		&i.MediaType,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (wa_id, from_jid, to_jid, content, media_type, timestamp)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at
`

type InsertMessageParams struct {
	WaID      string         `json:"wa_id"`
	FromJid   string         `json:"from_jid"`
	ToJid     string         `json:"to_jid"`
	Content   string         `json:"content"`
	MediaType sql.NullString `json:"media_type"`
	Timestamp int64          `json:"timestamp"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.WaID,
		arg.FromJid,
		arg.ToJid,
		arg.Content,
		arg.MediaType,
		arg.Timestamp,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WaID,
		&i.FromJid,
		&i.ToJid,
		&i.Content,
		&i.MediaType,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at FROM messages
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListMessagesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.WaID,
			&i.FromJid,
			&i.ToJid,
			&i.Content,
			&i.MediaType,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByJID = `-- name: ListMessagesByJID :many
SELECT id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at FROM messages
WHERE from_jid = ? OR to_jid = ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListMessagesByJIDParams struct {
	FromJid string `json:"from_jid"`
	ToJid   string `json:"to_jid"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListMessagesByJID(ctx context.Context, arg ListMessagesByJIDParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByJID,
		arg.FromJid,
		arg.ToJid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.WaID,
			&i.FromJid,
			&i.ToJid,
			&i.Content,
			&i.MediaType,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = ?, media_type = ?
WHERE id = ?
RETURNING id, wa_id, from_jid, to_jid, content, media_type, timestamp, created_at
`

type UpdateMessageParams struct {
	Content   string         `json:"content"`
	MediaType sql.NullString `json:"media_type"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessage, arg.Content, arg.MediaType, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.WaID,
		&i.FromJid,
		&i.ToJid,
		&i.Content,
		&i.MediaType,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}
