// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Message struct {
	ID        int64          `json:"id"`
	WaID      string         `json:"wa_id"`
	FromJid   string         `json:"from_jid"`
	ToJid     string         `json:"to_jid"`
	Content   string         `json:"content"`
	MediaType sql.NullString `json:"media_type"`
	Timestamp int64          `json:"timestamp"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Project struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	OwnerJid  string       `json:"owner_jid"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Reminder struct {
	ID          int64        `json:"id"`
	Jid         string       `json:"jid"`
	Message     string       `json:"message"`
	ScheduledAt time.Time    `json:"scheduled_at"`
	IsSent      sql.NullBool `json:"is_sent"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type WbsTask struct {
	ID        int64        `json:"id"`
	ProjectID int64        `json:"project_id"`
	Title     string       `json:"title"`
	Status    string       `json:"status"`
	DueDate   sql.NullTime `json:"due_date"`
	CreatedAt sql.NullTime `json:"created_at"`
}
