// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, owner_jid, status, created_at FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerJid,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (name, owner_jid, status)
VALUES (?, ?, ?)
RETURNING id, name, owner_jid, status, created_at
`

type InsertProjectParams struct {
	Name     string `json:"name"`
	OwnerJid string `json:"owner_jid"`
	Status   string `json:"status"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject, arg.Name, arg.OwnerJid, arg.Status)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerJid,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, owner_jid, status, created_at FROM projects
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerJid,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, name, owner_jid, status, created_at FROM projects
WHERE owner_jid = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsByOwnerParams struct {
	OwnerJid string `json:"owner_jid"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, arg ListProjectsByOwnerParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOwner, arg.OwnerJid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerJid,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByStatus = `-- name: ListProjectsByStatus :many
SELECT id, name, owner_jid, status, created_at FROM projects
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListProjectsByStatus(ctx context.Context, arg ListProjectsByStatusParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerJid,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = ?, status = ?
WHERE id = ?
RETURNING id, name, owner_jid, status, created_at
`

type UpdateProjectParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Status, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerJid,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
