// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlc

import (
	"context"
	"time"
)

const deleteReminder = `-- name: DeleteReminder :exec
DELETE FROM reminders WHERE id = ?
`

func (q *Queries) DeleteReminder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReminder, id)
	return err
}

const getReminderByID = `-- name: GetReminderByID :one
SELECT id, jid, message, scheduled_at, is_sent, created_at FROM reminders WHERE id = ? LIMIT 1
`

func (q *Queries) GetReminderByID(ctx context.Context, id int64) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, getReminderByID, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Jid,
		&i.Message,
		&i.ScheduledAt,
		&i.IsSent,
		&i.CreatedAt,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :one
INSERT INTO reminders (jid, message, scheduled_at)
VALUES (?, ?, ?)
RETURNING id, jid, message, scheduled_at, is_sent, created_at
`

type InsertReminderParams struct {
	Jid         string    `json:"jid"`
	Message     string    `json:"message"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, insertReminder, arg.Jid, arg.Message, arg.ScheduledAt)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Jid,
		&i.Message,
		&i.ScheduledAt,
		&i.IsSent,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingReminders = `-- name: ListPendingReminders :many
SELECT id, jid, message, scheduled_at, is_sent, created_at FROM reminders
WHERE is_sent = 0 AND scheduled_at <= ?
ORDER BY scheduled_at ASC
`

func (q *Queries) ListPendingReminders(ctx context.Context, scheduledAt time.Time) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReminders, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.Jid,
			&i.Message,
			&i.ScheduledAt,
			&i.IsSent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, jid, message, scheduled_at, is_sent, created_at FROM reminders
ORDER BY scheduled_at ASC
LIMIT ? OFFSET ?
`

type ListRemindersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listReminders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.Jid,
			&i.Message,
			&i.ScheduledAt,
			&i.IsSent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByJID = `-- name: ListRemindersByJID :many
SELECT id, jid, message, scheduled_at, is_sent, created_at FROM reminders
WHERE jid = ?
ORDER BY scheduled_at ASC
LIMIT ? OFFSET ?
`

type ListRemindersByJIDParams struct {
	Jid    string `json:"jid"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListRemindersByJID(ctx context.Context, arg ListRemindersByJIDParams) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersByJID, arg.Jid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.Jid,
			&i.Message,
			&i.ScheduledAt,
			&i.IsSent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderAsSent = `-- name: MarkReminderAsSent :exec
UPDATE reminders
SET is_sent = 1
WHERE id = ?
`

func (q *Queries) MarkReminderAsSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markReminderAsSent, id)
	return err
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders
SET message = ?, scheduled_at = ?
WHERE id = ?
RETURNING id, jid, message, scheduled_at, is_sent, created_at
`

type UpdateReminderParams struct {
	Message     string    `json:"message"`
	ScheduledAt time.Time `json:"scheduled_at"`
	ID          int64     `json:"id"`
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, updateReminder, arg.Message, arg.ScheduledAt, arg.ID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.Jid,
		&i.Message,
		&i.ScheduledAt,
		&i.IsSent,
		&i.CreatedAt,
	)
	return i, err
}
