// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wbs_tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteWBSTask = `-- name: DeleteWBSTask :exec
DELETE FROM wbs_tasks WHERE id = ?
`

func (q *Queries) DeleteWBSTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWBSTask, id)
	return err
}

const getWBSTaskByID = `-- name: GetWBSTaskByID :one
SELECT id, project_id, title, status, due_date, created_at FROM wbs_tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWBSTaskByID(ctx context.Context, id int64) (WbsTask, error) {
	row := q.db.QueryRowContext(ctx, getWBSTaskByID, id)
	var i WbsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertWBSTask = `-- name: InsertWBSTask :one
INSERT INTO wbs_tasks (project_id, title, status, due_date)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, title, status, due_date, created_at
`

type InsertWBSTaskParams struct {
	ProjectID int64        `json:"project_id"`
	Title     string       `json:"title"`
	Status    string       `json:"status"`
	DueDate   sql.NullTime `json:"due_date"`
}

func (q *Queries) InsertWBSTask(ctx context.Context, arg InsertWBSTaskParams) (WbsTask, error) {
	row := q.db.QueryRowContext(ctx, insertWBSTask,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.DueDate,
	)
	var i WbsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const listWBSTasks = `-- name: ListWBSTasks :many
SELECT id, project_id, title, status, due_date, created_at FROM wbs_tasks
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWBSTasksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListWBSTasks(ctx context.Context, arg ListWBSTasksParams) ([]WbsTask, error) {
	rows, err := q.db.QueryContext(ctx, listWBSTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WbsTask{}
	for rows.Next() {
		var i WbsTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWBSTasksByProject = `-- name: ListWBSTasksByProject :many
SELECT id, project_id, title, status, due_date, created_at FROM wbs_tasks
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWBSTasksByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListWBSTasksByProject(ctx context.Context, arg ListWBSTasksByProjectParams) ([]WbsTask, error) {
	rows, err := q.db.QueryContext(ctx, listWBSTasksByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WbsTask{}
	for rows.Next() {
		var i WbsTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWBSTasksByStatus = `-- name: ListWBSTasksByStatus :many
SELECT id, project_id, title, status, due_date, created_at FROM wbs_tasks
WHERE status = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListWBSTasksByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListWBSTasksByStatus(ctx context.Context, arg ListWBSTasksByStatusParams) ([]WbsTask, error) {
	rows, err := q.db.QueryContext(ctx, listWBSTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WbsTask{}
	for rows.Next() {
		var i WbsTask
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWBSTask = `-- name: UpdateWBSTask :one
UPDATE wbs_tasks
SET title = ?, status = ?, due_date = ?
WHERE id = ?
RETURNING id, project_id, title, status, due_date, created_at
`

type UpdateWBSTaskParams struct {
	Title   string       `json:"title"`
	Status  string       `json:"status"`
	DueDate sql.NullTime `json:"due_date"`
	ID      int64        `json:"id"`
}

func (q *Queries) UpdateWBSTask(ctx context.Context, arg UpdateWBSTaskParams) (WbsTask, error) {
	row := q.db.QueryRowContext(ctx, updateWBSTask,
		arg.Title,
		arg.Status,
		arg.DueDate,
		arg.ID,
	)
	var i WbsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}
